# Generated by Django 4.2.10 on 2024-02-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxy',
            options={'verbose_name': 'Proxy', 'verbose_name_plural': 'Proxies'},
        ),
    ]
